TRACK_WINDOW_X = 200
TRACK_WINDOW_Y = 200
TRACK_WINDOW_W = 280
TRACK_WINDOW_H = 280

TRACK_WINDOW = (TRACK_WINDOW_X, TRACK_WINDOW_Y, TRACK_WINDOW_W, TRACK_WINDOW_H)

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

COLLISION_MARGIN = 5
